server:
  port: 9090

spring:
  profiles:
    active: dev
  application:
    name: pcks-cross-configserver-core
  cloud:
    config:
      server:
        git:
          uri: https://github.com/packsendme/pcks-cross-config-core.git
          searchPaths: Develop
          label: develop