server:
  port: 9090

spring:
  profiles:
    active: dev
  application:
    name: packsendme-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/packsendme/packsendme-config-server
          searchPaths: Develop